### ISSUE TITLE
有按地域搜索关键词需求

### ISSUE THREAD

**Issue by johnqoe** [songgeb/BDIndexSpider#12]
您好：
     最近想做城市之间的相互联系，想通过相互搜索指数来体现；
     因此现在有个需求，按地域搜索关键词，（比如选择地域“天津”，搜索关键词“北京”）
     烦请各位老师能不能把这个需求加上，给你们打call！

**Comment by songgeb** [comment]
已加入该功能，参考最新master分支代码
