### ISSUE TITLE
无法识别图片中的数字

### ISSUE THREAD

**Issue by GUOxingyu3018** [songgeb/BDIndexSpider#15]
无论是自动下载后还是用工具都无法识别图片，无法输出图片代表的数字

**Comment by songgeb** [comment]
> 无论是自动下载后还是用工具都无法识别图片，无法输出图片代表的数字

可否贴一张数字图片到评论中，我看一下

**Comment by GUOxingyu3018** [comment]
![image](https://user-images.githubusercontent.com/32212421/47193379-20d8f280-d385-11e8-9223-a5e5b60544de.png)，有效结果内没有百度指数的数值。
![image](https://user-images.githubusercontent.com/32212421/47193427-6e555f80-d385-11e8-8864-68a00766911c.png)，这是数字图片。
我在想是不是我之前下载的安装过Tesseract-OCR 干扰了程序的识别，因为我的Tesseract-OCR 没有num.traineddata

**Comment by songgeb** [comment]
跟Tesseract-OCR无关。是图片达不到识别的精度。你按照readme中这个设置试一下。
![image](https://user-images.githubusercontent.com/5978164/47193539-13703800-d386-11e8-88f2-fdd6c83f2ee3.png)

**Comment by GUOxingyu3018** [comment]
万分感谢
